@startuml
interface BeanFactory{
    Object getBean(String name)
}

interface ApplicationContext{
    String[] getBeanDefinitionNames();
}

ApplicationContext --> BeanFactory

abstract class AbstractApplicationContext{

}

interface BeanDefinition{
}

interface BeanFactoryPostProcessor{

}

interface BeanPostProcessor{
}

interface SingletonBeanRegistry{
}

interface BeanDefinitionReader{}

interface BeanDefinitionRegistry{}

interface InstantiationStrategy{}


@enduml